export const color = {
    defaultBg: '#FAFBFD',
    defaultWhite: '#FFF',
    headerPurple: '#7C68EE',
    borderGray: '#F2F2F2',
    labelGray: '#818181',
    submitGray: '#292B29',
    errorRed: '#FF0000',
    loadingGray: '#969696',
    barBorderGray: '#EFEFEF',
    paginationGray: '#DFE3E8',
    disableGray: '#919EAB',
    detailsGray: '#B4B4B4',
    hoverPurple: '#E6E3FA',
    borderPurple: '#7C68EE',
    loaderTransparent: '#F3F3F3',
    loaderBlue: '#87ace8',
    heightGray: '#656565',
    abilityGray: '#ECECEC',
}
